use EPAM_Project
go
create table ContactsPhones(
	Id int PRIMARY KEY IDENTITY(1, 1),
	Contact int NOT NULL FOREIGN KEY REFERENCES Contacts(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	Phone int NOT NULL FOREIGN KEY REFERENCES Phones(Id) ON DELETE CASCADE ON UPDATE CASCADE
)